version: '3.1'
services:
  drupal:
    image: drupal:8-apache
    ports:
      - 8080:80
    volumes:
      - ./data/modules:/var/www/html/modules
      - ./data/profiles:/var/www/html/profiles
      - ./data/themes:/var/www/html/themes
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - /var/www/html/sites
    restart: always
  mysql:
      image: mysql:8.0
      container_name: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: unless-stopped
      env_file: .env
      volumes:
        - ./data/mysql:/var/lib/mysql